name: Output
on: issues
jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout/@v3
            - name: Getting Info
              run: echo '${{ github }}'

        